version: "3.11"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app
      - ./tech-blog:/home/data/tech-blog
    command: >
      sh -c "python main.py"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_TOKEN=${API_TOKEN}
